// Code generated by protoc-gen-go.
// source: proto/basic.proto
// DO NOT EDIT!

/*
Package dChannel is a generated protocol buffer package.

It is generated from these files:
	proto/basic.proto

It has these top-level messages:
	Signal
	String
	Bytes
	Bool
	Int8
	Int16
	Int32
	Int64
	Uint8
	Uint16
	Uint32
	Uint64
	Float32
	Float64
*/
package dChannel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Signal struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Signal) Reset()                    { *m = Signal{} }
func (m *Signal) String() string            { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()               {}
func (*Signal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signal) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type String struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *String) Reset()                    { *m = String{} }
func (m *String) String() string            { return proto.CompactTextString(m) }
func (*String) ProtoMessage()               {}
func (*String) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Bytes struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Bytes) Reset()                    { *m = Bytes{} }
func (m *Bytes) String() string            { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()               {}
func (*Bytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Bytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Bool struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Int8 struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Int8) Reset()                    { *m = Int8{} }
func (m *Int8) String() string            { return proto.CompactTextString(m) }
func (*Int8) ProtoMessage()               {}
func (*Int8) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Int8) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int16 struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Int16) Reset()                    { *m = Int16{} }
func (m *Int16) String() string            { return proto.CompactTextString(m) }
func (*Int16) ProtoMessage()               {}
func (*Int16) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Int16) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int32 struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Int32) Reset()                    { *m = Int32{} }
func (m *Int32) String() string            { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()               {}
func (*Int32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64 struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Int64) Reset()                    { *m = Int64{} }
func (m *Int64) String() string            { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()               {}
func (*Int64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint8 struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Uint8) Reset()                    { *m = Uint8{} }
func (m *Uint8) String() string            { return proto.CompactTextString(m) }
func (*Uint8) ProtoMessage()               {}
func (*Uint8) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Uint8) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint16 struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Uint16) Reset()                    { *m = Uint16{} }
func (m *Uint16) String() string            { return proto.CompactTextString(m) }
func (*Uint16) ProtoMessage()               {}
func (*Uint16) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Uint16) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint32 struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Uint32) Reset()                    { *m = Uint32{} }
func (m *Uint32) String() string            { return proto.CompactTextString(m) }
func (*Uint32) ProtoMessage()               {}
func (*Uint32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Uint32) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint64 struct {
	Value uint64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Uint64) Reset()                    { *m = Uint64{} }
func (m *Uint64) String() string            { return proto.CompactTextString(m) }
func (*Uint64) ProtoMessage()               {}
func (*Uint64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Uint64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Float32 struct {
	Value float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
}

func (m *Float32) Reset()                    { *m = Float32{} }
func (m *Float32) String() string            { return proto.CompactTextString(m) }
func (*Float32) ProtoMessage()               {}
func (*Float32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Float32) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Float64 struct {
	Value float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
}

func (m *Float64) Reset()                    { *m = Float64{} }
func (m *Float64) String() string            { return proto.CompactTextString(m) }
func (*Float64) ProtoMessage()               {}
func (*Float64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Float64) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Signal)(nil), "dChannel.Signal")
	proto.RegisterType((*String)(nil), "dChannel.String")
	proto.RegisterType((*Bytes)(nil), "dChannel.Bytes")
	proto.RegisterType((*Bool)(nil), "dChannel.Bool")
	proto.RegisterType((*Int8)(nil), "dChannel.Int8")
	proto.RegisterType((*Int16)(nil), "dChannel.Int16")
	proto.RegisterType((*Int32)(nil), "dChannel.Int32")
	proto.RegisterType((*Int64)(nil), "dChannel.Int64")
	proto.RegisterType((*Uint8)(nil), "dChannel.Uint8")
	proto.RegisterType((*Uint16)(nil), "dChannel.Uint16")
	proto.RegisterType((*Uint32)(nil), "dChannel.Uint32")
	proto.RegisterType((*Uint64)(nil), "dChannel.Uint64")
	proto.RegisterType((*Float32)(nil), "dChannel.Float32")
	proto.RegisterType((*Float64)(nil), "dChannel.Float64")
}

func init() { proto.RegisterFile("proto/basic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4a, 0x2c, 0xce, 0x4c, 0xd6, 0x03, 0xb3, 0x85, 0x38, 0x52, 0x9c, 0x33, 0x12,
	0xf3, 0xf2, 0x52, 0x73, 0x94, 0xe4, 0xb8, 0xd8, 0x82, 0x33, 0xd3, 0xf3, 0x12, 0x73, 0x84, 0x44,
	0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x82, 0x20, 0x1c,
	0xb0, 0x7c, 0x49, 0x51, 0x66, 0x5e, 0x3a, 0xaa, 0x3c, 0x27, 0x4c, 0x5e, 0x96, 0x8b, 0xd5, 0xa9,
	0xb2, 0x24, 0xb5, 0x18, 0x55, 0x9a, 0x07, 0x26, 0x2d, 0xc3, 0xc5, 0xe2, 0x94, 0x9f, 0x8f, 0xcb,
	0x70, 0x19, 0x2e, 0x16, 0xcf, 0xbc, 0x12, 0x0b, 0x54, 0x59, 0x56, 0x24, 0xa3, 0x3d, 0xf3, 0x4a,
	0x0c, 0xcd, 0xf0, 0x4a, 0x1b, 0x1b, 0xe1, 0x95, 0x36, 0x33, 0x41, 0x95, 0x66, 0x46, 0x92, 0x0e,
	0xcd, 0xc4, 0xb0, 0x9b, 0x17, 0xc9, 0xdb, 0x20, 0x69, 0x74, 0xcb, 0xd1, 0xe5, 0xd1, 0x6d, 0x47,
	0x97, 0x47, 0xb7, 0x9e, 0x05, 0x26, 0x2f, 0xcf, 0xc5, 0xee, 0x96, 0x93, 0x9f, 0x88, 0x61, 0x00,
	0x13, 0xba, 0x02, 0x74, 0x13, 0x18, 0xa1, 0x0a, 0x92, 0xd8, 0xc0, 0x31, 0x69, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x99, 0x1d, 0x9b, 0xe0, 0xde, 0x01, 0x00, 0x00,
}
